python ../main.py -e 5 -t nn_rhorho -i $RHORHO_DATA -f Variant-All --training_method soft_argmaxs --num_classes 3
python ../main.py -e 5 -t nn_rhorho -i $RHORHO_DATA -f Variant-All --training_method soft_argmaxs --num_classes 5
python ../main.py -e 5 -t nn_rhorho -i $RHORHO_DATA -f Variant-All --training_method soft_argmaxs --num_classes 7
python ../main.py -e 5 -t nn_rhorho -i $RHORHO_DATA -f Variant-All --training_method soft_argmaxs --num_classes 9
python ../main.py -e 5 -t nn_rhorho -i $RHORHO_DATA -f Variant-All --training_method soft_argmaxs --num_classes 11
python ../main.py -e 5 -t nn_rhorho -i $RHORHO_DATA -f Variant-All --training_method soft_argmaxs --num_classes 13
python ../main.py -e 5 -t nn_rhorho -i $RHORHO_DATA -f Variant-All --training_method soft_argmaxs --num_classes 15
python ../main.py -e 5 -t nn_rhorho -i $RHORHO_DATA -f Variant-All --training_method soft_argmaxs --num_classes 17
python ../main.py -e 5 -t nn_rhorho -i $RHORHO_DATA -f Variant-All --training_method soft_argmaxs --num_classes 19
python ../main.py -e 5 -t nn_rhorho -i $RHORHO_DATA -f Variant-All --training_method soft_argmaxs --num_classes 21
python ../main.py -e 5 -t nn_rhorho -i $RHORHO_DATA -f Variant-All --training_method soft_argmaxs --num_classes 23
python ../main.py -e 5 -t nn_rhorho -i $RHORHO_DATA -f Variant-All --training_method soft_argmaxs --num_classes 27
python ../main.py -e 5 -t nn_rhorho -i $RHORHO_DATA -f Variant-All --training_method soft_argmaxs --num_classes 29
python ../main.py -e 5 -t nn_rhorho -i $RHORHO_DATA -f Variant-All --training_method soft_argmaxs --num_classes 31
python ../main.py -e 5 -t nn_rhorho -i $RHORHO_DATA -f Variant-All --training_method soft_argmaxs --num_classes 33
python ../main.py -e 5 -t nn_rhorho -i $RHORHO_DATA -f Variant-All --training_method soft_argmaxs --num_classes 35
python ../main.py -e 5 -t nn_rhorho -i $RHORHO_DATA -f Variant-All --training_method soft_argmaxs --num_classes 37
python ../main.py -e 5 -t nn_rhorho -i $RHORHO_DATA -f Variant-All --training_method soft_argmaxs --num_classes 39
python ../main.py -e 5 -t nn_rhorho -i $RHORHO_DATA -f Variant-All --training_method soft_argmaxs --num_classes 41
python ../main.py -e 5 -t nn_rhorho -i $RHORHO_DATA -f Variant-All --training_method soft_argmaxs --num_classes 43
python ../main.py -e 5 -t nn_rhorho -i $RHORHO_DATA -f Variant-All --training_method soft_argmaxs --num_classes 45
python ../main.py -e 5 -t nn_rhorho -i $RHORHO_DATA -f Variant-All --training_method soft_argmaxs --num_classes 47
python ../main.py -e 5 -t nn_rhorho -i $RHORHO_DATA -f Variant-All --training_method soft_argmaxs --num_classes 49
python ../main.py -e 5 -t nn_rhorho -i $RHORHO_DATA -f Variant-All --training_method soft_argmaxs --num_classes 51

